fall quarter updates
stanford-centaur/stanford-centaur.github.io pull request #11
Opened 2024-09-27 21:57 UTC by limpa105

List of Updates 
- FMCAD paper news 
- Tutorial FM news 
- Graduated Ph.D. Students 
- Graduated Master Students
- Rachel headshot 
- New Sponsors
- Founding Sponsors
<img width="467" alt="Screenshot 2024-09-27 at 2 13 18 PM" src="https://github.com/user-attachments/assets/fa4c8495-65c0-47ea-8be2-cce59a5f2a0d">

List of Remaining Updates
- Classes page (waiting for responses)
- Rotating students (need to figure out how to add new class)
- Bachelor students

2024-09-27 22:40 UTC, barrettcw requested changes
Looks great - thanks!  Just a few minor comments

2024-09-27 22:40 UTC, barrettcw commented on _data/news_items.yaml
> +   Mathias Preiner, Andrew Reynolds and Yoni Zohar has been selected as a distinguished tutorial at  the <i> 26th International Symposium on Formal Methods </i> located in Milan, Italy!"
I am pro-Oxford comma

2024-09-27 22:40 UTC, barrettcw commented on _data/news_items.yaml
> +  excerpt: " Papers by Udayan Mandal, Ross Daly and Rachel Cleaveland as well as a tool paper 'SMT-D: New Strategies for Portfolio-Based SMT Solving' have been accepted to FMCAD2024. "
Oxford comma :)

2024-09-27 22:40 UTC, barrettcw commented on _data/people.yaml
> +  end: 2024
Well, since today is his last day, we might as well not add him now,

2024-09-27 22:40 UTC, barrettcw commented on affiliates_and_sponsors.md
> +
Let's just have a bulleted list without the categories (i.e., Platinum, Silver, etc.)

2024-09-27 22:40 UTC, barrettcw commented on _data/people.yaml
>    position: phd
Caleb has also graduated

2024-09-27 22:40 UTC, barrettcw commented on _data/people.yaml
> +  end: 2024
I guess we can add him as alumni :)

2024-09-27 22:40 UTC, barrettcw commented on _data/people.yaml
> +  now: Atlassian
We should also add Ben, Kaia, and Jibiana as alumni

2024-09-29 23:55 UTC, barrettcw requested changes
Almost there...

2024-09-29 23:55 UTC, barrettcw commented on _data/people.yaml
> +  now: Oxford
Ben is at Cambridge, not Oxford

2024-09-29 23:55 UTC, barrettcw commented on _data/people.yaml
> +  now: UCLA
So, Ying is currently at XAI, and will start at UCLA in a couple of years.  Maybe just put both?

2024-09-29 23:55 UTC, barrettcw commented on _data/people.yaml
> +- name: Sophia Andrews
Sophie not Sophia

2024-09-30 00:16 UTC, limpa105 commented on _data/people.yaml
> +- name: Sophia Andrews
Thank you for catching these mistakes!

2024-09-30 00:21 UTC, barrettcw approved these changes
LGTM!

2024-09-30 16:07 UTC, merged